In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import KNNImputer

In [4]:
dict = {'Maths':[85,91,np.nan,67],
        'Chemistry':[59,90,77,np.nan],
        'Physics':[np.nan,68,49,95],
        'Biology':[71,60,79,np.nan]}

In [5]:
dict

{'Maths': [85, 91, nan, 67],
 'Chemistry': [59, 90, 77, nan],
 'Physics': [nan, 68, 49, 95],
 'Biology': [71, 60, 79, nan]}

In [6]:
Before_imputation = pd.DataFrame(dict)
Before_imputation

Maths  Chemistry  Physics  Biology
0   85.0       59.0      NaN     71.0
1   91.0       90.0     68.0     60.0
2    NaN       77.0     49.0     79.0
3   67.0        NaN     95.0      NaN

In [7]:
imputer = KNNImputer(n_neighbors=2)
After_imputation = imputer.fit_transform(Before_imputation)
After_imputation

array([[85. , 59. , 72. , 71. ],
       [91. , 90. , 68. , 60. ],
       [88. , 77. , 49. , 79. ],
       [67. , 74.5, 95. , 65.5]])

In [9]:
dict1 = {'Class 1':[1, 3, np.nan,4],
        'Class 2':[4,6,np.nan,8],
        'Class 3':[np.nan,6,5,1],
        'Class 4':[7,6,9,np.nan]}

In [10]:
dict1

{'Class 1': [1, 3, nan, 4],
 'Class 2': [4, 6, nan, 8],
 'Class 3': [nan, 6, 5, 1],
 'Class 4': [7, 6, 9, nan]}

In [11]:
Before_imputation = pd.DataFrame(dict)
Before_imputation

Class 1  Class 2  Class 3  Class 4
0      1.0      4.0      NaN      7.0
1      3.0      6.0      6.0      6.0
2      NaN      NaN      5.0      9.0
3      4.0      8.0      1.0      NaN

In [12]:
imputer = KNNImputer(n_neighbors=2)
After_imputation = imputer.fit_transform(Before_imputation)
After_imputation

array([[1. , 4. , 5.5, 7. ],
       [3. , 6. , 6. , 6. ],
       [2. , 5. , 5. , 9. ],
       [4. , 8. , 1. , 6.5]])

In [13]:
df = pd.DataFrame(dict)

In [14]:
df

Class 1  Class 2  Class 3  Class 4
0      1.0      4.0      NaN      7.0
1      3.0      6.0      6.0      6.0
2      NaN      NaN      5.0      9.0
3      4.0      8.0      1.0      NaN

In [15]:
df.isna().sum()

Class 1    1
Class 2    1
Class 3    1
Class 4    1
dtype: int64

In [16]:
df.isna().sum().sum()

4

In [17]:
shape=df.shape
(df.isna().sum().sum())/(shape[0]*shape[1])*100

25.0

In [18]:
df1=df.dropna()
df1

Class 1  Class 2  Class 3  Class 4
1      3.0      6.0      6.0      6.0

In [19]:
df1=df.dropna(thresh=3,axis=0)

In [20]:
df1

Class 1  Class 2  Class 3  Class 4
0      1.0      4.0      NaN      7.0
1      3.0      6.0      6.0      6.0
3      4.0      8.0      1.0      NaN

In [22]:
df2=df.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

import or create required dataset

In [55]:
dz = {'name':['Root', 'Stark' , 'john' ,'marsh' ,'sum'],
'age': ['31' ,'37' ,'29' ,'35' ,'28'],
'department': ['navy' ,'army' ,'np.nan' ,'army' ,'navy'],
'color_code': ['white' ,'comouflage' ,'np.nan' ,'comouflage' ,'blue']}
dz



{'name': ['Root', 'Stark', 'john', 'marsh', 'sum'],
 'age': ['31', '37', '29', '35', '28'],
 'department': ['navy', 'army', 'np.nan', 'army', 'navy'],
 'color_code': ['white', 'comouflage', 'np.nan', 'comouflage', 'blue']}

In [56]:
dz=pd.DataFrame(dz)
dz

name age department  color_code
0   Root  31       navy       white
1  Stark  37       army  comouflage
2   john  29     np.nan      np.nan
3  marsh  35       army  comouflage
4    sum  28       navy        blue

In [57]:
dz["department"]=dz.department.map({"navy":0,"army":1})
dz["color_code"]=dz.color_code.map({"blue":2,"comouflage":3 ,"white":4})
dz

name age  department  color_code
0   Root  31         0.0         4.0
1  Stark  37         1.0         3.0
2   john  29         NaN         NaN
3  marsh  35         1.0         3.0
4    sum  28         0.0         2.0

In [59]:
dz1 = dz[['age','department','color_code']]

In [60]:
dz1

age  department  color_code
0  31         0.0         4.0
1  37         1.0         3.0
2  29         NaN         NaN
3  35         1.0         3.0
4  28         0.0         2.0

Apply KNN Imputer

In [61]:
imputer = KNNImputer(n_neighbors=2)
dz1 = imputer.fit_transform(dz1)
dz1

array([[31.,  0.,  4.],
       [37.,  1.,  3.],
       [29.,  0.,  3.],
       [35.,  1.,  3.],
       [28.,  0.,  2.]])